# Generated by Django 5.0.6 on 2024-05-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('quantity', models.IntegerField(default=0)),
                ('image_url', models.URLField(null=True)),
                ('stripe_product_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
